### ISSUE TITLE
feat: auto-update validator and miner code using pm2

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-bittensor#245] opened 2024-09-09 17:57 UTC
## Problem 

When a release goes out miner or validator code does not auto-update

This is an implementation ticket for #208

**Comment by Luka-Loncar** [comment] 2024-09-13 14:09
Added to v1.0 as agreed.

**Comment by Luka-Loncar** [comment] 2024-09-13 16:06
Duplicate of #246

**Closed by Luka-Loncar** 2024-09-13 16:06 UTC
Labels: feature
